#!/bin/bash

# Extract the start and stop position from found-domains.tab
# Result columns: 
#    Domain Name,
#    Domain Accession, 
#    Sequence Accession,
#    Start Position (ali coord from)
#    Stop Position (ali coord to)
cat found-domains.tab | grep -v "^#" | \
sed 's/  */\t/g'  | cut -f 1,2,4,18,19
