#!/bin/bash

# Fail on unbound variables. E.g. when arguents are not given
set -u

# Takes 1 argument - the found domains tab file
fasta_in=$1                                    
basename=$(basename -s .extract $fasta_in*.extract)

# Use the extract the start and stop position from found-domains.tab
# Result columns: 
#    Domain Name (column 1),
#    Domain Accession (column 2), 
#    Sequence Accession (column 3),
#    Start Position (env coord from - column 4)
#    Stop Position (env coord to - column 5)

# make directory for the results
mkdir -p ./results

# make a blastdb from the input fasta
makeblastdb -in $fasta_in -parse_seqids -dbtype prot

# make a blastdb from the input fasta

awk '{OFS="\t"}{print $1,$4"-"$5}' $fasta_in*.extract > range.txt

blastdbcmd -db $fasta_in -entry_batch range.txt -outfmt "%f" -out ./results/$basename.extracted-seq.fa

rm range.txt